/********************************************************************
* mzDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error mzDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablemzDict();
extern void G__cpp_setup_inheritancemzDict();
extern void G__cpp_setup_typetablemzDict();
extern void G__cpp_setup_memvarmzDict();
extern void G__cpp_setup_globalmzDict();
extern void G__cpp_setup_memfuncmzDict();
extern void G__cpp_setup_funcmzDict();
extern void G__set_cpp_environmentmzDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "mz.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__mzDictLN_TClass;
extern G__linked_taginfo G__mzDictLN_TBuffer;
extern G__linked_taginfo G__mzDictLN_TMemberInspector;
extern G__linked_taginfo G__mzDictLN_TObject;
extern G__linked_taginfo G__mzDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__mzDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__mzDictLN_TList;
extern G__linked_taginfo G__mzDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__mzDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__mzDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__mzDictLN_TFile;
extern G__linked_taginfo G__mzDictLN_TTree;
extern G__linked_taginfo G__mzDictLN_TBranch;
extern G__linked_taginfo G__mzDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__mzDictLN_TSelector;
extern G__linked_taginfo G__mzDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__mzDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__mzDictLN_TH1F;
extern G__linked_taginfo G__mzDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__mzDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__mzDictLN_TH2F;
extern G__linked_taginfo G__mzDictLN_mz;

/* STUB derived class for protected member access */
